name: upload to PyPI

on: 
  push:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Installs setup and upgrades pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt
          python3 -m setup.py sdist bdist_wheel
          python3 -m pip install twine
          
      - name: Test with unittest
        run: |
          cd tests
          python3 -m unittest discover
          cd ..
          
      - name: build and upload to PyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER_NAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      
      
      
